// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module adc_regs_mod (
        input wire clk,
        input wire rst,

        input wire s_cpuif_req,
        input wire s_cpuif_req_is_wr,
        input wire [15:0] s_cpuif_addr,
        input wire [7:0] s_cpuif_wr_data,
        input wire [7:0] s_cpuif_wr_biten,
        output wire s_cpuif_req_stall_wr,
        output wire s_cpuif_req_stall_rd,
        output wire s_cpuif_rd_ack,
        output wire s_cpuif_rd_err,
        output wire [7:0] s_cpuif_rd_data,
        output wire s_cpuif_wr_ack,
        output wire s_cpuif_wr_err,

        input adc_regs_mod_pkg::adc_regs__in_t hwif_in,
        output adc_regs_mod_pkg::adc_regs__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [15:0] cpuif_addr;
    logic [7:0] cpuif_wr_data;
    logic [7:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [7:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    assign cpuif_req = s_cpuif_req;
    assign cpuif_req_is_wr = s_cpuif_req_is_wr;
    assign cpuif_addr = s_cpuif_addr;
    assign cpuif_wr_data = s_cpuif_wr_data;
    assign cpuif_wr_biten = s_cpuif_wr_biten;
    assign s_cpuif_req_stall_wr = cpuif_req_stall_wr;
    assign s_cpuif_req_stall_rd = cpuif_req_stall_rd;
    assign s_cpuif_rd_ack = cpuif_rd_ack;
    assign s_cpuif_rd_err = cpuif_rd_err;
    assign s_cpuif_rd_data = cpuif_rd_data;
    assign s_cpuif_wr_ack = cpuif_wr_ack;
    assign s_cpuif_wr_err = cpuif_wr_err;

    logic cpuif_req_masked;
    logic external_req;
    logic external_pending;
    logic external_wr_ack;
    logic external_rd_ack;
    always_ff @(posedge clk) begin
        if(rst) begin
            external_pending <= '0;
        end else begin
            if(external_req & ~external_wr_ack & ~external_rd_ack) external_pending <= '1;
            else if(external_wr_ack | external_rd_ack) external_pending <= '0;
            `ifndef SYNTHESIS
                assert_bad_ext_wr_ack: assert(!external_wr_ack || (external_pending | external_req))
                    else $error("An external wr_ack strobe was asserted when no external request was active");
                assert_bad_ext_rd_ack: assert(!external_rd_ack || (external_pending | external_req))
                    else $error("An external rd_ack strobe was asserted when no external request was active");
            `endif
        end
    end

    // Read latency > write latency. May need to delay next write that follows a read
    logic [0:0] cpuif_req_stall_sr;
    always_ff @(posedge clk) begin
        if(rst) begin
            cpuif_req_stall_sr <= '0;
        end else if(cpuif_req && !cpuif_req_is_wr) begin
            cpuif_req_stall_sr <= '1;
        end else begin
            cpuif_req_stall_sr <= (cpuif_req_stall_sr >> 'd1);
        end
    end
    assign cpuif_req_stall_rd = external_pending;
    assign cpuif_req_stall_wr = cpuif_req_stall_sr[0] | external_pending;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic ADC_OUTPUT_MEM;
        logic [1:0] SH_CTRL;
        logic [1:0] INT1_CTRL;
        logic [1:0] INT2_CTRL;
        logic [1:0] FFT_CTRL;
        logic [1:0] ADC_CTRL;
        logic [1:0] CONVERSION_FLAGS;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic decoded_strb_is_external;

    logic [15:0] decoded_addr;

    logic decoded_req;
    logic decoded_req_is_wr;
    logic [7:0] decoded_wr_data;
    logic [7:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_invalid_rw;
        automatic logic is_external;
        is_external = '0;
        is_valid_addr = '1; // No error checking on valid address access
        is_invalid_rw = '0;
        decoded_reg_strb.ADC_OUTPUT_MEM = cpuif_req_masked & (cpuif_addr >= 16'h0) & (cpuif_addr <= 16'h0 + 16'h7fff) & !cpuif_req_is_wr;
        is_external |= cpuif_req_masked & (cpuif_addr >= 16'h0) & (cpuif_addr <= 16'h0 + 16'h7fff) & !cpuif_req_is_wr;
        decoded_reg_strb.SH_CTRL[0] = cpuif_req_masked & (cpuif_addr == 16'h8000);
        decoded_reg_strb.SH_CTRL[1] = cpuif_req_masked & (cpuif_addr == 16'h8001);
        decoded_reg_strb.INT1_CTRL[0] = cpuif_req_masked & (cpuif_addr == 16'h8002);
        decoded_reg_strb.INT1_CTRL[1] = cpuif_req_masked & (cpuif_addr == 16'h8003);
        decoded_reg_strb.INT2_CTRL[0] = cpuif_req_masked & (cpuif_addr == 16'h8004);
        decoded_reg_strb.INT2_CTRL[1] = cpuif_req_masked & (cpuif_addr == 16'h8005);
        decoded_reg_strb.FFT_CTRL[0] = cpuif_req_masked & (cpuif_addr == 16'h8006);
        decoded_reg_strb.FFT_CTRL[1] = cpuif_req_masked & (cpuif_addr == 16'h8007);
        decoded_reg_strb.ADC_CTRL[0] = cpuif_req_masked & (cpuif_addr == 16'h8008);
        decoded_reg_strb.ADC_CTRL[1] = cpuif_req_masked & (cpuif_addr == 16'h8009);
        decoded_reg_strb.CONVERSION_FLAGS[0] = cpuif_req_masked & (cpuif_addr == 16'h800a) & !cpuif_req_is_wr;
        decoded_reg_strb.CONVERSION_FLAGS[1] = cpuif_req_masked & (cpuif_addr == 16'h800b) & !cpuif_req_is_wr;
        decoded_err = (~is_valid_addr | is_invalid_rw) & decoded_req;
        decoded_strb_is_external = is_external;
        external_req = is_external;
    end

    // Pass down signals to next stage
    assign decoded_addr = cpuif_addr;

    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic [7:0] next;
                logic load_next;
            } N_ACTIVE_CYCLES;
            struct {
                logic [7:0] next;
                logic load_next;
            } N_PASSIVE_CYCLES;
        } SH_CTRL;
        struct {
            struct {
                logic [7:0] next;
                logic load_next;
            } N_ACTIVE_CYCLES;
            struct {
                logic [7:0] next;
                logic load_next;
            } N_PASSIVE_CYCLES;
        } INT1_CTRL;
        struct {
            struct {
                logic [7:0] next;
                logic load_next;
            } N_ACTIVE_CYCLES;
            struct {
                logic [7:0] next;
                logic load_next;
            } N_PASSIVE_CYCLES;
        } INT2_CTRL;
        struct {
            struct {
                logic [2:0] next;
                logic load_next;
            } OSR_POWER;
            struct {
                logic [3:0] next;
                logic load_next;
            } NFFT_POWER;
            struct {
                logic next;
                logic load_next;
            } INCREMENTAL_MODE_EN;
            struct {
                logic next;
                logic load_next;
            } NOISE_SHAPING_EN;
            struct {
                logic [1:0] next;
                logic load_next;
            } N_QUANTIZER_BITS;
            struct {
                logic next;
                logic load_next;
            } DWA_EN;
            struct {
                logic [3:0] next;
                logic load_next;
            } DELAY_LINE_CTRL;
        } FFT_CTRL;
        struct {
            struct {
                logic next;
                logic load_next;
            } START_CONVERSION;
        } ADC_CTRL;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic [7:0] value;
            } N_ACTIVE_CYCLES;
            struct {
                logic [7:0] value;
            } N_PASSIVE_CYCLES;
        } SH_CTRL;
        struct {
            struct {
                logic [7:0] value;
            } N_ACTIVE_CYCLES;
            struct {
                logic [7:0] value;
            } N_PASSIVE_CYCLES;
        } INT1_CTRL;
        struct {
            struct {
                logic [7:0] value;
            } N_ACTIVE_CYCLES;
            struct {
                logic [7:0] value;
            } N_PASSIVE_CYCLES;
        } INT2_CTRL;
        struct {
            struct {
                logic [2:0] value;
            } OSR_POWER;
            struct {
                logic [3:0] value;
            } NFFT_POWER;
            struct {
                logic value;
            } INCREMENTAL_MODE_EN;
            struct {
                logic value;
            } NOISE_SHAPING_EN;
            struct {
                logic [1:0] value;
            } N_QUANTIZER_BITS;
            struct {
                logic value;
            } DWA_EN;
            struct {
                logic [3:0] value;
            } DELAY_LINE_CTRL;
        } FFT_CTRL;
        struct {
            struct {
                logic value;
            } START_CONVERSION;
        } ADC_CTRL;
    } field_storage_t;
    field_storage_t field_storage;

    // External region: adc_regs.ADC_OUTPUT_MEM
    assign hwif_out.ADC_OUTPUT_MEM.req = decoded_reg_strb.ADC_OUTPUT_MEM;
    assign hwif_out.ADC_OUTPUT_MEM.addr = decoded_addr[14:0];
    assign hwif_out.ADC_OUTPUT_MEM.req_is_wr = decoded_req_is_wr;
    assign hwif_out.ADC_OUTPUT_MEM.wr_data = decoded_wr_data;
    assign hwif_out.ADC_OUTPUT_MEM.wr_biten = decoded_wr_biten;
    // Field: adc_regs.SH_CTRL.N_ACTIVE_CYCLES
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SH_CTRL.N_ACTIVE_CYCLES.value;
        load_next_c = '0;
        if(decoded_reg_strb.SH_CTRL[0] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SH_CTRL.N_ACTIVE_CYCLES.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end
        field_combo.SH_CTRL.N_ACTIVE_CYCLES.next = next_c;
        field_combo.SH_CTRL.N_ACTIVE_CYCLES.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.SH_CTRL.N_ACTIVE_CYCLES.value <= 8'h1;
        end else begin
            if(field_combo.SH_CTRL.N_ACTIVE_CYCLES.load_next) begin
                field_storage.SH_CTRL.N_ACTIVE_CYCLES.value <= field_combo.SH_CTRL.N_ACTIVE_CYCLES.next;
            end
        end
    end
    assign hwif_out.SH_CTRL.N_ACTIVE_CYCLES.value = field_storage.SH_CTRL.N_ACTIVE_CYCLES.value;
    // Field: adc_regs.SH_CTRL.N_PASSIVE_CYCLES
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.SH_CTRL.N_PASSIVE_CYCLES.value;
        load_next_c = '0;
        if(decoded_reg_strb.SH_CTRL[1] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.SH_CTRL.N_PASSIVE_CYCLES.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end
        field_combo.SH_CTRL.N_PASSIVE_CYCLES.next = next_c;
        field_combo.SH_CTRL.N_PASSIVE_CYCLES.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.SH_CTRL.N_PASSIVE_CYCLES.value <= 8'h0;
        end else begin
            if(field_combo.SH_CTRL.N_PASSIVE_CYCLES.load_next) begin
                field_storage.SH_CTRL.N_PASSIVE_CYCLES.value <= field_combo.SH_CTRL.N_PASSIVE_CYCLES.next;
            end
        end
    end
    assign hwif_out.SH_CTRL.N_PASSIVE_CYCLES.value = field_storage.SH_CTRL.N_PASSIVE_CYCLES.value;
    // Field: adc_regs.INT1_CTRL.N_ACTIVE_CYCLES
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.INT1_CTRL.N_ACTIVE_CYCLES.value;
        load_next_c = '0;
        if(decoded_reg_strb.INT1_CTRL[0] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.INT1_CTRL.N_ACTIVE_CYCLES.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end
        field_combo.INT1_CTRL.N_ACTIVE_CYCLES.next = next_c;
        field_combo.INT1_CTRL.N_ACTIVE_CYCLES.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.INT1_CTRL.N_ACTIVE_CYCLES.value <= 8'h1;
        end else begin
            if(field_combo.INT1_CTRL.N_ACTIVE_CYCLES.load_next) begin
                field_storage.INT1_CTRL.N_ACTIVE_CYCLES.value <= field_combo.INT1_CTRL.N_ACTIVE_CYCLES.next;
            end
        end
    end
    assign hwif_out.INT1_CTRL.N_ACTIVE_CYCLES.value = field_storage.INT1_CTRL.N_ACTIVE_CYCLES.value;
    // Field: adc_regs.INT1_CTRL.N_PASSIVE_CYCLES
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.INT1_CTRL.N_PASSIVE_CYCLES.value;
        load_next_c = '0;
        if(decoded_reg_strb.INT1_CTRL[1] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.INT1_CTRL.N_PASSIVE_CYCLES.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end
        field_combo.INT1_CTRL.N_PASSIVE_CYCLES.next = next_c;
        field_combo.INT1_CTRL.N_PASSIVE_CYCLES.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.INT1_CTRL.N_PASSIVE_CYCLES.value <= 8'h0;
        end else begin
            if(field_combo.INT1_CTRL.N_PASSIVE_CYCLES.load_next) begin
                field_storage.INT1_CTRL.N_PASSIVE_CYCLES.value <= field_combo.INT1_CTRL.N_PASSIVE_CYCLES.next;
            end
        end
    end
    assign hwif_out.INT1_CTRL.N_PASSIVE_CYCLES.value = field_storage.INT1_CTRL.N_PASSIVE_CYCLES.value;
    // Field: adc_regs.INT2_CTRL.N_ACTIVE_CYCLES
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.INT2_CTRL.N_ACTIVE_CYCLES.value;
        load_next_c = '0;
        if(decoded_reg_strb.INT2_CTRL[0] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.INT2_CTRL.N_ACTIVE_CYCLES.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end
        field_combo.INT2_CTRL.N_ACTIVE_CYCLES.next = next_c;
        field_combo.INT2_CTRL.N_ACTIVE_CYCLES.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.INT2_CTRL.N_ACTIVE_CYCLES.value <= 8'h1;
        end else begin
            if(field_combo.INT2_CTRL.N_ACTIVE_CYCLES.load_next) begin
                field_storage.INT2_CTRL.N_ACTIVE_CYCLES.value <= field_combo.INT2_CTRL.N_ACTIVE_CYCLES.next;
            end
        end
    end
    assign hwif_out.INT2_CTRL.N_ACTIVE_CYCLES.value = field_storage.INT2_CTRL.N_ACTIVE_CYCLES.value;
    // Field: adc_regs.INT2_CTRL.N_PASSIVE_CYCLES
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.INT2_CTRL.N_PASSIVE_CYCLES.value;
        load_next_c = '0;
        if(decoded_reg_strb.INT2_CTRL[1] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.INT2_CTRL.N_PASSIVE_CYCLES.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end
        field_combo.INT2_CTRL.N_PASSIVE_CYCLES.next = next_c;
        field_combo.INT2_CTRL.N_PASSIVE_CYCLES.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.INT2_CTRL.N_PASSIVE_CYCLES.value <= 8'h0;
        end else begin
            if(field_combo.INT2_CTRL.N_PASSIVE_CYCLES.load_next) begin
                field_storage.INT2_CTRL.N_PASSIVE_CYCLES.value <= field_combo.INT2_CTRL.N_PASSIVE_CYCLES.next;
            end
        end
    end
    assign hwif_out.INT2_CTRL.N_PASSIVE_CYCLES.value = field_storage.INT2_CTRL.N_PASSIVE_CYCLES.value;
    // Field: adc_regs.FFT_CTRL.OSR_POWER
    always_comb begin
        automatic logic [2:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.FFT_CTRL.OSR_POWER.value;
        load_next_c = '0;
        if(decoded_reg_strb.FFT_CTRL[0] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.FFT_CTRL.OSR_POWER.value & ~decoded_wr_biten[2:0]) | (decoded_wr_data[2:0] & decoded_wr_biten[2:0]);
            load_next_c = '1;
        end
        field_combo.FFT_CTRL.OSR_POWER.next = next_c;
        field_combo.FFT_CTRL.OSR_POWER.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.FFT_CTRL.OSR_POWER.value <= 3'h0;
        end else begin
            if(field_combo.FFT_CTRL.OSR_POWER.load_next) begin
                field_storage.FFT_CTRL.OSR_POWER.value <= field_combo.FFT_CTRL.OSR_POWER.next;
            end
        end
    end
    assign hwif_out.FFT_CTRL.OSR_POWER.value = field_storage.FFT_CTRL.OSR_POWER.value;
    // Field: adc_regs.FFT_CTRL.NFFT_POWER
    always_comb begin
        automatic logic [3:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.FFT_CTRL.NFFT_POWER.value;
        load_next_c = '0;
        if(decoded_reg_strb.FFT_CTRL[0] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.FFT_CTRL.NFFT_POWER.value & ~decoded_wr_biten[6:3]) | (decoded_wr_data[6:3] & decoded_wr_biten[6:3]);
            load_next_c = '1;
        end
        field_combo.FFT_CTRL.NFFT_POWER.next = next_c;
        field_combo.FFT_CTRL.NFFT_POWER.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.FFT_CTRL.NFFT_POWER.value <= 4'h0;
        end else begin
            if(field_combo.FFT_CTRL.NFFT_POWER.load_next) begin
                field_storage.FFT_CTRL.NFFT_POWER.value <= field_combo.FFT_CTRL.NFFT_POWER.next;
            end
        end
    end
    assign hwif_out.FFT_CTRL.NFFT_POWER.value = field_storage.FFT_CTRL.NFFT_POWER.value;
    // Field: adc_regs.FFT_CTRL.INCREMENTAL_MODE_EN
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.FFT_CTRL.INCREMENTAL_MODE_EN.value;
        load_next_c = '0;
        if(decoded_reg_strb.FFT_CTRL[0] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.FFT_CTRL.INCREMENTAL_MODE_EN.value & ~decoded_wr_biten[7:7]) | (decoded_wr_data[7:7] & decoded_wr_biten[7:7]);
            load_next_c = '1;
        end
        field_combo.FFT_CTRL.INCREMENTAL_MODE_EN.next = next_c;
        field_combo.FFT_CTRL.INCREMENTAL_MODE_EN.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.FFT_CTRL.INCREMENTAL_MODE_EN.value <= 1'h0;
        end else begin
            if(field_combo.FFT_CTRL.INCREMENTAL_MODE_EN.load_next) begin
                field_storage.FFT_CTRL.INCREMENTAL_MODE_EN.value <= field_combo.FFT_CTRL.INCREMENTAL_MODE_EN.next;
            end
        end
    end
    assign hwif_out.FFT_CTRL.INCREMENTAL_MODE_EN.value = field_storage.FFT_CTRL.INCREMENTAL_MODE_EN.value;
    // Field: adc_regs.FFT_CTRL.NOISE_SHAPING_EN
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.FFT_CTRL.NOISE_SHAPING_EN.value;
        load_next_c = '0;
        if(decoded_reg_strb.FFT_CTRL[1] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.FFT_CTRL.NOISE_SHAPING_EN.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.FFT_CTRL.NOISE_SHAPING_EN.next = next_c;
        field_combo.FFT_CTRL.NOISE_SHAPING_EN.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.FFT_CTRL.NOISE_SHAPING_EN.value <= 1'h0;
        end else begin
            if(field_combo.FFT_CTRL.NOISE_SHAPING_EN.load_next) begin
                field_storage.FFT_CTRL.NOISE_SHAPING_EN.value <= field_combo.FFT_CTRL.NOISE_SHAPING_EN.next;
            end
        end
    end
    assign hwif_out.FFT_CTRL.NOISE_SHAPING_EN.value = field_storage.FFT_CTRL.NOISE_SHAPING_EN.value;
    // Field: adc_regs.FFT_CTRL.N_QUANTIZER_BITS
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.FFT_CTRL.N_QUANTIZER_BITS.value;
        load_next_c = '0;
        if(decoded_reg_strb.FFT_CTRL[1] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.FFT_CTRL.N_QUANTIZER_BITS.value & ~decoded_wr_biten[2:1]) | (decoded_wr_data[2:1] & decoded_wr_biten[2:1]);
            load_next_c = '1;
        end
        field_combo.FFT_CTRL.N_QUANTIZER_BITS.next = next_c;
        field_combo.FFT_CTRL.N_QUANTIZER_BITS.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.FFT_CTRL.N_QUANTIZER_BITS.value <= 2'h0;
        end else begin
            if(field_combo.FFT_CTRL.N_QUANTIZER_BITS.load_next) begin
                field_storage.FFT_CTRL.N_QUANTIZER_BITS.value <= field_combo.FFT_CTRL.N_QUANTIZER_BITS.next;
            end
        end
    end
    assign hwif_out.FFT_CTRL.N_QUANTIZER_BITS.value = field_storage.FFT_CTRL.N_QUANTIZER_BITS.value;
    // Field: adc_regs.FFT_CTRL.DWA_EN
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.FFT_CTRL.DWA_EN.value;
        load_next_c = '0;
        if(decoded_reg_strb.FFT_CTRL[1] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.FFT_CTRL.DWA_EN.value & ~decoded_wr_biten[3:3]) | (decoded_wr_data[3:3] & decoded_wr_biten[3:3]);
            load_next_c = '1;
        end
        field_combo.FFT_CTRL.DWA_EN.next = next_c;
        field_combo.FFT_CTRL.DWA_EN.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.FFT_CTRL.DWA_EN.value <= 1'h0;
        end else begin
            if(field_combo.FFT_CTRL.DWA_EN.load_next) begin
                field_storage.FFT_CTRL.DWA_EN.value <= field_combo.FFT_CTRL.DWA_EN.next;
            end
        end
    end
    assign hwif_out.FFT_CTRL.DWA_EN.value = field_storage.FFT_CTRL.DWA_EN.value;
    // Field: adc_regs.FFT_CTRL.DELAY_LINE_CTRL
    always_comb begin
        automatic logic [3:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.FFT_CTRL.DELAY_LINE_CTRL.value;
        load_next_c = '0;
        if(decoded_reg_strb.FFT_CTRL[1] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.FFT_CTRL.DELAY_LINE_CTRL.value & ~decoded_wr_biten[7:4]) | (decoded_wr_data[7:4] & decoded_wr_biten[7:4]);
            load_next_c = '1;
        end
        field_combo.FFT_CTRL.DELAY_LINE_CTRL.next = next_c;
        field_combo.FFT_CTRL.DELAY_LINE_CTRL.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.FFT_CTRL.DELAY_LINE_CTRL.value <= 4'h0;
        end else begin
            if(field_combo.FFT_CTRL.DELAY_LINE_CTRL.load_next) begin
                field_storage.FFT_CTRL.DELAY_LINE_CTRL.value <= field_combo.FFT_CTRL.DELAY_LINE_CTRL.next;
            end
        end
    end
    assign hwif_out.FFT_CTRL.DELAY_LINE_CTRL.value = field_storage.FFT_CTRL.DELAY_LINE_CTRL.value;
    // Field: adc_regs.ADC_CTRL.START_CONVERSION
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.ADC_CTRL.START_CONVERSION.value;
        load_next_c = '0;
        if(decoded_reg_strb.ADC_CTRL[0] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.ADC_CTRL.START_CONVERSION.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end else if(hwif_in.ADC_CTRL.START_CONVERSION.hwclr) begin // HW Clear
            next_c = '0;
            load_next_c = '1;
        end
        field_combo.ADC_CTRL.START_CONVERSION.next = next_c;
        field_combo.ADC_CTRL.START_CONVERSION.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.ADC_CTRL.START_CONVERSION.value <= 1'h0;
        end else begin
            if(field_combo.ADC_CTRL.START_CONVERSION.load_next) begin
                field_storage.ADC_CTRL.START_CONVERSION.value <= field_combo.ADC_CTRL.START_CONVERSION.next;
            end
        end
    end
    assign hwif_out.ADC_CTRL.START_CONVERSION.value = field_storage.ADC_CTRL.START_CONVERSION.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    always_comb begin
        automatic logic wr_ack;
        wr_ack = '0;
        wr_ack |= hwif_in.ADC_OUTPUT_MEM.wr_ack;
        external_wr_ack = wr_ack;
    end
    assign cpuif_wr_ack = external_wr_ack | (decoded_req & decoded_req_is_wr & ~decoded_strb_is_external);
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------
    logic readback_external_rd_ack_c;
    always_comb begin
        automatic logic rd_ack;
        rd_ack = '0;
        rd_ack |= hwif_in.ADC_OUTPUT_MEM.rd_ack;
        readback_external_rd_ack_c = rd_ack;
    end

    logic readback_external_rd_ack;

    assign readback_external_rd_ack = readback_external_rd_ack_c;

    logic readback_err;
    logic readback_done;
    logic [7:0] readback_data;

    // Assign readback values to a flattened array
    logic [7:0] readback_array[12];
    assign readback_array[0] = hwif_in.ADC_OUTPUT_MEM.rd_ack ? hwif_in.ADC_OUTPUT_MEM.rd_data : '0;
    assign readback_array[1][7:0] = (decoded_reg_strb.SH_CTRL[0] && !decoded_req_is_wr) ? field_storage.SH_CTRL.N_ACTIVE_CYCLES.value : '0;
    assign readback_array[2][7:0] = (decoded_reg_strb.SH_CTRL[1] && !decoded_req_is_wr) ? field_storage.SH_CTRL.N_PASSIVE_CYCLES.value : '0;
    assign readback_array[3][7:0] = (decoded_reg_strb.INT1_CTRL[0] && !decoded_req_is_wr) ? field_storage.INT1_CTRL.N_ACTIVE_CYCLES.value : '0;
    assign readback_array[4][7:0] = (decoded_reg_strb.INT1_CTRL[1] && !decoded_req_is_wr) ? field_storage.INT1_CTRL.N_PASSIVE_CYCLES.value : '0;
    assign readback_array[5][7:0] = (decoded_reg_strb.INT2_CTRL[0] && !decoded_req_is_wr) ? field_storage.INT2_CTRL.N_ACTIVE_CYCLES.value : '0;
    assign readback_array[6][7:0] = (decoded_reg_strb.INT2_CTRL[1] && !decoded_req_is_wr) ? field_storage.INT2_CTRL.N_PASSIVE_CYCLES.value : '0;
    assign readback_array[7][2:0] = (decoded_reg_strb.FFT_CTRL[0] && !decoded_req_is_wr) ? field_storage.FFT_CTRL.OSR_POWER.value : '0;
    assign readback_array[7][6:3] = (decoded_reg_strb.FFT_CTRL[0] && !decoded_req_is_wr) ? field_storage.FFT_CTRL.NFFT_POWER.value : '0;
    assign readback_array[7][7:7] = (decoded_reg_strb.FFT_CTRL[0] && !decoded_req_is_wr) ? field_storage.FFT_CTRL.INCREMENTAL_MODE_EN.value : '0;
    assign readback_array[8][0:0] = (decoded_reg_strb.FFT_CTRL[1] && !decoded_req_is_wr) ? field_storage.FFT_CTRL.NOISE_SHAPING_EN.value : '0;
    assign readback_array[8][2:1] = (decoded_reg_strb.FFT_CTRL[1] && !decoded_req_is_wr) ? field_storage.FFT_CTRL.N_QUANTIZER_BITS.value : '0;
    assign readback_array[8][3:3] = (decoded_reg_strb.FFT_CTRL[1] && !decoded_req_is_wr) ? field_storage.FFT_CTRL.DWA_EN.value : '0;
    assign readback_array[8][7:4] = (decoded_reg_strb.FFT_CTRL[1] && !decoded_req_is_wr) ? field_storage.FFT_CTRL.DELAY_LINE_CTRL.value : '0;
    assign readback_array[9][0:0] = (decoded_reg_strb.ADC_CTRL[0] && !decoded_req_is_wr) ? field_storage.ADC_CTRL.START_CONVERSION.value : '0;
    assign readback_array[9][1:1] = (decoded_reg_strb.ADC_CTRL[0] && !decoded_req_is_wr) ? hwif_in.ADC_CTRL.SYNC_RESET_RB.next : '0;
    assign readback_array[9][5:2] = (decoded_reg_strb.ADC_CTRL[0] && !decoded_req_is_wr) ? hwif_in.ADC_CTRL.MAIN_STATE_RB.next : '0;
    assign readback_array[9][7:6] = '0;
    assign readback_array[10][7:0] = (decoded_reg_strb.CONVERSION_FLAGS[0] && !decoded_req_is_wr) ? hwif_in.CONVERSION_FLAGS.N_VALID_SAMPLES.next[7:0] : '0;
    assign readback_array[11][6:0] = (decoded_reg_strb.CONVERSION_FLAGS[1] && !decoded_req_is_wr) ? hwif_in.CONVERSION_FLAGS.N_VALID_SAMPLES.next[14:8] : '0;
    assign readback_array[11][7:7] = (decoded_reg_strb.CONVERSION_FLAGS[1] && !decoded_req_is_wr) ? hwif_in.CONVERSION_FLAGS.PREVIOUS_CONVERSION_CORRUPTED.next : '0;

    // Reduce the array
    always_comb begin
        automatic logic [7:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr & ~decoded_strb_is_external;
        readback_err = '0;
        readback_data_var = '0;
        for(int i=0; i<12; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    always_ff @(posedge clk) begin
        if(rst) begin
            cpuif_rd_ack <= '0;
            cpuif_rd_data <= '0;
            cpuif_rd_err <= '0;
            external_rd_ack <= '0;
        end else begin
            external_rd_ack <= readback_external_rd_ack;
            cpuif_rd_ack <= readback_done | readback_external_rd_ack;
            cpuif_rd_data <= readback_data;
            cpuif_rd_err <= readback_err;
        end
    end

endmodule
