// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package adc_regs_mod_pkg;

    localparam ADC_REGS_MOD_DATA_WIDTH = 8;
    localparam ADC_REGS_MOD_MIN_ADDR_WIDTH = 16;
    localparam ADC_REGS_MOD_SIZE = 'h800c;

    typedef struct {
        logic rd_ack;
        logic [7:0] rd_data;
        logic wr_ack;
    } adc_regs__ADC_OUTPUT_MEM__external__in_t;

    typedef struct {
        logic hwclr;
    } adc_regs__ADC_CTRL__START_CONVERSION__in_t;

    typedef struct {
        logic next;
    } adc_regs__ADC_CTRL__SYNC_RESET_RB__in_t;

    typedef struct {
        logic [3:0] next;
    } adc_regs__ADC_CTRL__MAIN_STATE_RB__in_t;

    typedef struct {
        adc_regs__ADC_CTRL__START_CONVERSION__in_t START_CONVERSION;
        adc_regs__ADC_CTRL__SYNC_RESET_RB__in_t SYNC_RESET_RB;
        adc_regs__ADC_CTRL__MAIN_STATE_RB__in_t MAIN_STATE_RB;
    } adc_regs__ADC_CTRL__in_t;

    typedef struct {
        logic [14:0] next;
    } adc_regs__CONVERSION_FLAGS__N_VALID_SAMPLES__in_t;

    typedef struct {
        logic next;
    } adc_regs__CONVERSION_FLAGS__PREVIOUS_CONVERSION_CORRUPTED__in_t;

    typedef struct {
        adc_regs__CONVERSION_FLAGS__N_VALID_SAMPLES__in_t N_VALID_SAMPLES;
        adc_regs__CONVERSION_FLAGS__PREVIOUS_CONVERSION_CORRUPTED__in_t PREVIOUS_CONVERSION_CORRUPTED;
    } adc_regs__CONVERSION_FLAGS__in_t;

    typedef struct {
        adc_regs__ADC_OUTPUT_MEM__external__in_t ADC_OUTPUT_MEM;
        adc_regs__ADC_CTRL__in_t ADC_CTRL;
        adc_regs__CONVERSION_FLAGS__in_t CONVERSION_FLAGS;
    } adc_regs__in_t;

    typedef struct {
        logic req;
        logic [14:0] addr;
        logic req_is_wr;
        logic [7:0] wr_data;
        logic [7:0] wr_biten;
    } adc_regs__ADC_OUTPUT_MEM__external__out_t;

    typedef struct {
        logic [7:0] value;
    } adc_regs__active_passive_reg__N_ACTIVE_CYCLES__out_t;

    typedef struct {
        logic [7:0] value;
    } adc_regs__active_passive_reg__N_PASSIVE_CYCLES__out_t;

    typedef struct {
        adc_regs__active_passive_reg__N_ACTIVE_CYCLES__out_t N_ACTIVE_CYCLES;
        adc_regs__active_passive_reg__N_PASSIVE_CYCLES__out_t N_PASSIVE_CYCLES;
    } adc_regs__active_passive_reg__out_t;

    typedef struct {
        logic [2:0] value;
    } adc_regs__FFT_CTRL__OSR_POWER__out_t;

    typedef struct {
        logic [3:0] value;
    } adc_regs__FFT_CTRL__NFFT_POWER__out_t;

    typedef struct {
        logic value;
    } adc_regs__FFT_CTRL__INCREMENTAL_MODE_EN__out_t;

    typedef struct {
        logic value;
    } adc_regs__FFT_CTRL__NOISE_SHAPING_EN__out_t;

    typedef struct {
        logic [1:0] value;
    } adc_regs__FFT_CTRL__N_QUANTIZER_BITS__out_t;

    typedef struct {
        logic value;
    } adc_regs__FFT_CTRL__DWA_EN__out_t;

    typedef struct {
        logic [3:0] value;
    } adc_regs__FFT_CTRL__DELAY_LINE_CTRL__out_t;

    typedef struct {
        adc_regs__FFT_CTRL__OSR_POWER__out_t OSR_POWER;
        adc_regs__FFT_CTRL__NFFT_POWER__out_t NFFT_POWER;
        adc_regs__FFT_CTRL__INCREMENTAL_MODE_EN__out_t INCREMENTAL_MODE_EN;
        adc_regs__FFT_CTRL__NOISE_SHAPING_EN__out_t NOISE_SHAPING_EN;
        adc_regs__FFT_CTRL__N_QUANTIZER_BITS__out_t N_QUANTIZER_BITS;
        adc_regs__FFT_CTRL__DWA_EN__out_t DWA_EN;
        adc_regs__FFT_CTRL__DELAY_LINE_CTRL__out_t DELAY_LINE_CTRL;
    } adc_regs__FFT_CTRL__out_t;

    typedef struct {
        logic value;
    } adc_regs__ADC_CTRL__START_CONVERSION__out_t;

    typedef struct {
        adc_regs__ADC_CTRL__START_CONVERSION__out_t START_CONVERSION;
    } adc_regs__ADC_CTRL__out_t;

    typedef struct {
        adc_regs__ADC_OUTPUT_MEM__external__out_t ADC_OUTPUT_MEM;
        adc_regs__active_passive_reg__out_t SH_CTRL;
        adc_regs__active_passive_reg__out_t INT1_CTRL;
        adc_regs__active_passive_reg__out_t INT2_CTRL;
        adc_regs__FFT_CTRL__out_t FFT_CTRL;
        adc_regs__ADC_CTRL__out_t ADC_CTRL;
    } adc_regs__out_t;
endpackage
