
// This file was autogenerated by PeakRDL-uvm
package adc_regs_pkg;
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    
    // reg - top::NFFT_CTRL
    class top__NFFT_CTRL extends uvm_reg;
        rand uvm_reg_field NFFT_POWER;
        rand uvm_reg_field DWA_EN;

        function new(string name = "top__NFFT_CTRL");
            super.new(name, 16, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.NFFT_POWER = new("NFFT_POWER");
            this.NFFT_POWER.configure(this, 15, 0, "RW", 0, 'h0, 1, 1, 0);
            this.DWA_EN = new("DWA_EN");
            this.DWA_EN.configure(this, 1, 15, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : top__NFFT_CTRL

    // reg - top::OSR
    class top__OSR extends uvm_reg;
        rand uvm_reg_field OSR_POWER;

        function new(string name = "top__OSR");
            super.new(name, 8, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.OSR_POWER = new("OSR_POWER");
            this.OSR_POWER.configure(this, 8, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : top__OSR

    // reg - top::active_reg
    class top__active_reg extends uvm_reg;
        rand uvm_reg_field N_CYCLES;

        function new(string name = "top__active_reg");
            super.new(name, 8, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.N_CYCLES = new("N_CYCLES");
            this.N_CYCLES.configure(this, 8, 0, "RW", 0, 'h1, 1, 1, 0);
        endfunction : build
    endclass : top__active_reg

    // reg - top::passive_reg
    class top__passive_reg extends uvm_reg;
        rand uvm_reg_field N_CYCLES;

        function new(string name = "top__passive_reg");
            super.new(name, 8, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.N_CYCLES = new("N_CYCLES");
            this.N_CYCLES.configure(this, 8, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : top__passive_reg

    // reg - top::SAR_CTRL
    class top__SAR_CTRL extends uvm_reg;
        rand uvm_reg_field DELAY_LINE_CTRL;

        function new(string name = "top__SAR_CTRL");
            super.new(name, 8, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.DELAY_LINE_CTRL = new("DELAY_LINE_CTRL");
            this.DELAY_LINE_CTRL.configure(this, 8, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : top__SAR_CTRL

    // reg - top::ADC_MODE_CTRL
    class top__ADC_MODE_CTRL extends uvm_reg;
        rand uvm_reg_field INPUT_MODE;
        rand uvm_reg_field VCM_SINGLE_ENDED;

        function new(string name = "top__ADC_MODE_CTRL");
            super.new(name, 8, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.INPUT_MODE = new("INPUT_MODE");
            this.INPUT_MODE.configure(this, 1, 0, "RW", 0, 'h0, 1, 1, 0);
            this.VCM_SINGLE_ENDED = new("VCM_SINGLE_ENDED");
            this.VCM_SINGLE_ENDED.configure(this, 4, 1, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : top__ADC_MODE_CTRL

    // reg - top::ADC_CTRL_wr
    class top__ADC_CTRL_wr extends uvm_reg;
        rand uvm_reg_field SAR_EN;
        rand uvm_reg_field NFFT_EN;

        function new(string name = "top__ADC_CTRL_wr");
            super.new(name, 8, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.SAR_EN = new("SAR_EN");
            this.SAR_EN.configure(this, 1, 0, "WO", 0, 'h0, 1, 1, 0);
            this.NFFT_EN = new("NFFT_EN");
            this.NFFT_EN.configure(this, 1, 1, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : top__ADC_CTRL_wr

    // reg - top::ADC_CTRL_rd
    class top__ADC_CTRL_rd extends uvm_reg;
        rand uvm_reg_field SAR_EN;
        rand uvm_reg_field NFFT_EN;
        rand uvm_reg_field MAIN_STATE_RB;

        function new(string name = "top__ADC_CTRL_rd");
            super.new(name, 8, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.SAR_EN = new("SAR_EN");
            this.SAR_EN.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            this.NFFT_EN = new("NFFT_EN");
            this.NFFT_EN.configure(this, 1, 1, "RO", 1, 'h0, 1, 1, 0);
            this.MAIN_STATE_RB = new("MAIN_STATE_RB");
            this.MAIN_STATE_RB.configure(this, 3, 2, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : top__ADC_CTRL_rd

    // reg - top::CLKGEN_DRP_0
    class top__CLKGEN_DRP_0 extends uvm_reg;
        rand uvm_reg_field CLKGEN_DRP_DADDR;

        function new(string name = "top__CLKGEN_DRP_0");
            super.new(name, 8, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.CLKGEN_DRP_DADDR = new("CLKGEN_DRP_DADDR");
            this.CLKGEN_DRP_DADDR.configure(this, 7, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : top__CLKGEN_DRP_0

    // reg - top::CLKGEN_DRP_1
    class top__CLKGEN_DRP_1 extends uvm_reg;
        rand uvm_reg_field CLKGEN_DRP_RD_EN;
        rand uvm_reg_field CLKGEN_DRP_WR_EN;
        rand uvm_reg_field CLKGEN_DRP_DEN;

        function new(string name = "top__CLKGEN_DRP_1");
            super.new(name, 8, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.CLKGEN_DRP_RD_EN = new("CLKGEN_DRP_RD_EN");
            this.CLKGEN_DRP_RD_EN.configure(this, 1, 0, "RW", 0, 'h0, 1, 1, 0);
            this.CLKGEN_DRP_WR_EN = new("CLKGEN_DRP_WR_EN");
            this.CLKGEN_DRP_WR_EN.configure(this, 1, 1, "RW", 0, 'h0, 1, 1, 0);
            this.CLKGEN_DRP_DEN = new("CLKGEN_DRP_DEN");
            this.CLKGEN_DRP_DEN.configure(this, 1, 2, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : top__CLKGEN_DRP_1

    // reg - top::CLKGEN_DRP_2
    class top__CLKGEN_DRP_2 extends uvm_reg;
        rand uvm_reg_field CLKGEN_DRP_DI;

        function new(string name = "top__CLKGEN_DRP_2");
            super.new(name, 16, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.CLKGEN_DRP_DI = new("CLKGEN_DRP_DI");
            this.CLKGEN_DRP_DI.configure(this, 16, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : top__CLKGEN_DRP_2

    // reg - top::CLKGEN_DRP_3
    class top__CLKGEN_DRP_3 extends uvm_reg;
        rand uvm_reg_field CLKGEN_DRP_DO;

        function new(string name = "top__CLKGEN_DRP_3");
            super.new(name, 16, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.CLKGEN_DRP_DO = new("CLKGEN_DRP_DO");
            this.CLKGEN_DRP_DO.configure(this, 16, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : top__CLKGEN_DRP_3

    // mem - top::adc_output_mem
    class top__adc_output_mem extends uvm_reg_block;
        rand uvm_mem m_mem;
        
        function new(string name = "top__adc_output_mem");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 2.0, UVM_NO_ENDIAN);
            this.m_mem = new("m_mem", 65536, 16, "RO");
            this.m_mem.configure(this);
            this.default_map.add_mem(this.m_mem, 0);
        endfunction : build
    endclass : top__adc_output_mem

    // addrmap - top
    class top extends uvm_reg_block;
        rand top__NFFT_CTRL NFFT_CTRL;
        rand top__OSR OSR;
        rand top__active_reg SH_ACTIVE;
        rand top__passive_reg SH_PASSIVE;
        rand top__active_reg INT1_ACTIVE;
        rand top__passive_reg INT1_PASSIVE;
        rand top__active_reg INT2_ACTIVE;
        rand top__passive_reg INT2_PASSIVE;
        rand top__SAR_CTRL SAR_CTRL;
        rand top__ADC_MODE_CTRL ADC_MODE_CTRL;
        rand top__ADC_CTRL_wr ADC_CTRL_wr;
        rand top__ADC_CTRL_rd ADC_CTRL_rd;
        rand top__CLKGEN_DRP_0 CLKGEN_DRP_0;
        rand top__CLKGEN_DRP_1 CLKGEN_DRP_1;
        rand top__CLKGEN_DRP_2 CLKGEN_DRP_2;
        rand top__CLKGEN_DRP_3 CLKGEN_DRP_3;
        rand top__adc_output_mem adc_output_mem;

        function new(string name = "top");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 2, UVM_NO_ENDIAN);
            this.NFFT_CTRL = new("NFFT_CTRL");
            this.NFFT_CTRL.configure(this);

            this.NFFT_CTRL.build();
            this.default_map.add_reg(this.NFFT_CTRL, 'h0);
            this.OSR = new("OSR");
            this.OSR.configure(this);

            this.OSR.build();
            this.default_map.add_reg(this.OSR, 'h2);
            this.SH_ACTIVE = new("SH_ACTIVE");
            this.SH_ACTIVE.configure(this);

            this.SH_ACTIVE.build();
            this.default_map.add_reg(this.SH_ACTIVE, 'h3);
            this.SH_PASSIVE = new("SH_PASSIVE");
            this.SH_PASSIVE.configure(this);

            this.SH_PASSIVE.build();
            this.default_map.add_reg(this.SH_PASSIVE, 'h4);
            this.INT1_ACTIVE = new("INT1_ACTIVE");
            this.INT1_ACTIVE.configure(this);

            this.INT1_ACTIVE.build();
            this.default_map.add_reg(this.INT1_ACTIVE, 'h5);
            this.INT1_PASSIVE = new("INT1_PASSIVE");
            this.INT1_PASSIVE.configure(this);

            this.INT1_PASSIVE.build();
            this.default_map.add_reg(this.INT1_PASSIVE, 'h6);
            this.INT2_ACTIVE = new("INT2_ACTIVE");
            this.INT2_ACTIVE.configure(this);

            this.INT2_ACTIVE.build();
            this.default_map.add_reg(this.INT2_ACTIVE, 'h7);
            this.INT2_PASSIVE = new("INT2_PASSIVE");
            this.INT2_PASSIVE.configure(this);

            this.INT2_PASSIVE.build();
            this.default_map.add_reg(this.INT2_PASSIVE, 'h8);
            this.SAR_CTRL = new("SAR_CTRL");
            this.SAR_CTRL.configure(this);

            this.SAR_CTRL.build();
            this.default_map.add_reg(this.SAR_CTRL, 'h9);
            this.ADC_MODE_CTRL = new("ADC_MODE_CTRL");
            this.ADC_MODE_CTRL.configure(this);

            this.ADC_MODE_CTRL.build();
            this.default_map.add_reg(this.ADC_MODE_CTRL, 'ha);
            this.ADC_CTRL_wr = new("ADC_CTRL_wr");
            this.ADC_CTRL_wr.configure(this);

            this.ADC_CTRL_wr.build();
            this.default_map.add_reg(this.ADC_CTRL_wr, 'hb);
            this.ADC_CTRL_rd = new("ADC_CTRL_rd");
            this.ADC_CTRL_rd.configure(this);

            this.ADC_CTRL_rd.build();
            this.default_map.add_reg(this.ADC_CTRL_rd, 'hb);
            this.CLKGEN_DRP_0 = new("CLKGEN_DRP_0");
            this.CLKGEN_DRP_0.configure(this);

            this.CLKGEN_DRP_0.build();
            this.default_map.add_reg(this.CLKGEN_DRP_0, 'hc);
            this.CLKGEN_DRP_1 = new("CLKGEN_DRP_1");
            this.CLKGEN_DRP_1.configure(this);

            this.CLKGEN_DRP_1.build();
            this.default_map.add_reg(this.CLKGEN_DRP_1, 'hd);
            this.CLKGEN_DRP_2 = new("CLKGEN_DRP_2");
            this.CLKGEN_DRP_2.configure(this);

            this.CLKGEN_DRP_2.build();
            this.default_map.add_reg(this.CLKGEN_DRP_2, 'he);
            this.CLKGEN_DRP_3 = new("CLKGEN_DRP_3");
            this.CLKGEN_DRP_3.configure(this);

            this.CLKGEN_DRP_3.build();
            this.default_map.add_reg(this.CLKGEN_DRP_3, 'h10);
            this.adc_output_mem = new("adc_output_mem");
            this.adc_output_mem.configure(this);
            this.adc_output_mem.build();
            this.default_map.add_submap(this.adc_output_mem.default_map, 'h20000);
        endfunction : build
    endclass : top

endpackage: adc_regs_pkg
