
// This file was autogenerated by PeakRDL-uvm
package adc_regs_pkg;
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    
    // reg - adc_regs::NFFT_CTRL
    class adc_regs__NFFT_CTRL extends uvm_reg;
        rand uvm_reg_field NFFT_POWER;
        rand uvm_reg_field DWA_EN;

        function new(string name = "adc_regs__NFFT_CTRL");
            super.new(name, 16, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.NFFT_POWER = new("NFFT_POWER");
            this.NFFT_POWER.configure(this, 15, 0, "RW", 0, 'h0, 1, 1, 0);
            this.DWA_EN = new("DWA_EN");
            this.DWA_EN.configure(this, 1, 15, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : adc_regs__NFFT_CTRL

    // reg - adc_regs::OSR
    class adc_regs__OSR extends uvm_reg;
        rand uvm_reg_field OSR_POWER;

        function new(string name = "adc_regs__OSR");
            super.new(name, 16, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.OSR_POWER = new("OSR_POWER");
            this.OSR_POWER.configure(this, 8, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : adc_regs__OSR

    // reg - adc_regs::active_passive_reg
    class adc_regs__active_passive_reg extends uvm_reg;
        rand uvm_reg_field N_ACTIVE_CYCLES;
        rand uvm_reg_field N_PASSIVE_CYCLES;

        function new(string name = "adc_regs__active_passive_reg");
            super.new(name, 16, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.N_ACTIVE_CYCLES = new("N_ACTIVE_CYCLES");
            this.N_ACTIVE_CYCLES.configure(this, 8, 0, "RW", 0, 'h1, 1, 1, 0);
            this.N_PASSIVE_CYCLES = new("N_PASSIVE_CYCLES");
            this.N_PASSIVE_CYCLES.configure(this, 8, 8, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : adc_regs__active_passive_reg

    // reg - adc_regs::SAR_CTRL
    class adc_regs__SAR_CTRL extends uvm_reg;
        rand uvm_reg_field INPUT_MODE;
        rand uvm_reg_field VCM_SINGLE_ENDED;
        rand uvm_reg_field DELAY_LINE_CTRL;
        rand uvm_reg_field N_QUANTIZER_BITS;

        function new(string name = "adc_regs__SAR_CTRL");
            super.new(name, 16, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.INPUT_MODE = new("INPUT_MODE");
            this.INPUT_MODE.configure(this, 1, 0, "RW", 0, 'h0, 1, 1, 0);
            this.VCM_SINGLE_ENDED = new("VCM_SINGLE_ENDED");
            this.VCM_SINGLE_ENDED.configure(this, 4, 1, "RW", 0, 'h0, 1, 1, 0);
            this.DELAY_LINE_CTRL = new("DELAY_LINE_CTRL");
            this.DELAY_LINE_CTRL.configure(this, 4, 5, "RW", 0, 'h0, 1, 1, 0);
            this.N_QUANTIZER_BITS = new("N_QUANTIZER_BITS");
            this.N_QUANTIZER_BITS.configure(this, 2, 9, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : adc_regs__SAR_CTRL

    // reg - adc_regs::ADC_CTRL_wr
    class adc_regs__ADC_CTRL_wr extends uvm_reg;
        rand uvm_reg_field SAR_EN;
        rand uvm_reg_field NFFT_EN;

        function new(string name = "adc_regs__ADC_CTRL_wr");
            super.new(name, 16, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.SAR_EN = new("SAR_EN");
            this.SAR_EN.configure(this, 1, 0, "WO", 0, 'h0, 1, 1, 0);
            this.NFFT_EN = new("NFFT_EN");
            this.NFFT_EN.configure(this, 1, 1, "WO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : adc_regs__ADC_CTRL_wr

    // reg - adc_regs::ADC_CTRL_rd
    class adc_regs__ADC_CTRL_rd extends uvm_reg;
        rand uvm_reg_field SAR_EN;
        rand uvm_reg_field NFFT_EN;
        rand uvm_reg_field MAIN_STATE_RB;

        function new(string name = "adc_regs__ADC_CTRL_rd");
            super.new(name, 16, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.SAR_EN = new("SAR_EN");
            this.SAR_EN.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            this.NFFT_EN = new("NFFT_EN");
            this.NFFT_EN.configure(this, 1, 1, "RO", 1, 'h0, 1, 1, 0);
            this.MAIN_STATE_RB = new("MAIN_STATE_RB");
            this.MAIN_STATE_RB.configure(this, 4, 2, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : adc_regs__ADC_CTRL_rd

    // reg - adc_regs::CLKGEN_DRP_0
    class adc_regs__CLKGEN_DRP_0 extends uvm_reg;
        rand uvm_reg_field CLKGEN_DRP_RD_EN;
        rand uvm_reg_field CLKGEN_DRP_WR_EN;
        rand uvm_reg_field CLKGEN_DRP_DEN;
        rand uvm_reg_field CLKGEN_DRP_DADDR;

        function new(string name = "adc_regs__CLKGEN_DRP_0");
            super.new(name, 16, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.CLKGEN_DRP_RD_EN = new("CLKGEN_DRP_RD_EN");
            this.CLKGEN_DRP_RD_EN.configure(this, 1, 0, "RW", 0, 'h0, 1, 1, 0);
            this.CLKGEN_DRP_WR_EN = new("CLKGEN_DRP_WR_EN");
            this.CLKGEN_DRP_WR_EN.configure(this, 1, 1, "RW", 0, 'h0, 1, 1, 0);
            this.CLKGEN_DRP_DEN = new("CLKGEN_DRP_DEN");
            this.CLKGEN_DRP_DEN.configure(this, 1, 2, "RW", 0, 'h0, 1, 1, 0);
            this.CLKGEN_DRP_DADDR = new("CLKGEN_DRP_DADDR");
            this.CLKGEN_DRP_DADDR.configure(this, 7, 3, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : adc_regs__CLKGEN_DRP_0

    // reg - adc_regs::CLKGEN_DRP_2
    class adc_regs__CLKGEN_DRP_2 extends uvm_reg;
        rand uvm_reg_field CLKGEN_DRP_DI;

        function new(string name = "adc_regs__CLKGEN_DRP_2");
            super.new(name, 16, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.CLKGEN_DRP_DI = new("CLKGEN_DRP_DI");
            this.CLKGEN_DRP_DI.configure(this, 16, 0, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : adc_regs__CLKGEN_DRP_2

    // reg - adc_regs::CLKGEN_DRP_3
    class adc_regs__CLKGEN_DRP_3 extends uvm_reg;
        rand uvm_reg_field CLKGEN_DRP_DO;

        function new(string name = "adc_regs__CLKGEN_DRP_3");
            super.new(name, 16, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.CLKGEN_DRP_DO = new("CLKGEN_DRP_DO");
            this.CLKGEN_DRP_DO.configure(this, 16, 0, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : adc_regs__CLKGEN_DRP_3

    // mem - adc_regs::adc_output_mem
    class adc_regs__adc_output_mem extends uvm_reg_block;
        rand uvm_mem m_mem;
        
        function new(string name = "adc_regs__adc_output_mem");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 2.0, UVM_NO_ENDIAN);
            this.m_mem = new("m_mem", 32768, 16, "RO");
            this.m_mem.configure(this);
            this.default_map.add_mem(this.m_mem, 0);
        endfunction : build
    endclass : adc_regs__adc_output_mem

    // addrmap - adc_regs
    class adc_regs extends uvm_reg_block;
        rand adc_regs__NFFT_CTRL NFFT_CTRL;
        rand adc_regs__OSR OSR;
        rand adc_regs__active_passive_reg SH_CTRL;
        rand adc_regs__active_passive_reg INT1_CTRL;
        rand adc_regs__active_passive_reg INT2_CTRL;
        rand adc_regs__SAR_CTRL SAR_CTRL;
        rand adc_regs__ADC_CTRL_wr ADC_CTRL_wr;
        rand adc_regs__ADC_CTRL_rd ADC_CTRL_rd;
        rand adc_regs__CLKGEN_DRP_0 CLKGEN_DRP_0;
        rand adc_regs__CLKGEN_DRP_2 CLKGEN_DRP_2;
        rand adc_regs__CLKGEN_DRP_3 CLKGEN_DRP_3;
        rand adc_regs__adc_output_mem adc_output_mem;

        function new(string name = "adc_regs");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 2, UVM_NO_ENDIAN);
            this.NFFT_CTRL = new("NFFT_CTRL");
            this.NFFT_CTRL.configure(this);

            this.NFFT_CTRL.build();
            this.default_map.add_reg(this.NFFT_CTRL, 'h0);
            this.OSR = new("OSR");
            this.OSR.configure(this);

            this.OSR.build();
            this.default_map.add_reg(this.OSR, 'h2);
            this.SH_CTRL = new("SH_CTRL");
            this.SH_CTRL.configure(this);

            this.SH_CTRL.build();
            this.default_map.add_reg(this.SH_CTRL, 'h4);
            this.INT1_CTRL = new("INT1_CTRL");
            this.INT1_CTRL.configure(this);

            this.INT1_CTRL.build();
            this.default_map.add_reg(this.INT1_CTRL, 'h6);
            this.INT2_CTRL = new("INT2_CTRL");
            this.INT2_CTRL.configure(this);

            this.INT2_CTRL.build();
            this.default_map.add_reg(this.INT2_CTRL, 'h8);
            this.SAR_CTRL = new("SAR_CTRL");
            this.SAR_CTRL.configure(this);

            this.SAR_CTRL.build();
            this.default_map.add_reg(this.SAR_CTRL, 'ha);
            this.ADC_CTRL_wr = new("ADC_CTRL_wr");
            this.ADC_CTRL_wr.configure(this);

            this.ADC_CTRL_wr.build();
            this.default_map.add_reg(this.ADC_CTRL_wr, 'hc);
            this.ADC_CTRL_rd = new("ADC_CTRL_rd");
            this.ADC_CTRL_rd.configure(this);

            this.ADC_CTRL_rd.build();
            this.default_map.add_reg(this.ADC_CTRL_rd, 'hc);
            this.CLKGEN_DRP_0 = new("CLKGEN_DRP_0");
            this.CLKGEN_DRP_0.configure(this);

            this.CLKGEN_DRP_0.build();
            this.default_map.add_reg(this.CLKGEN_DRP_0, 'h10);
            this.CLKGEN_DRP_2 = new("CLKGEN_DRP_2");
            this.CLKGEN_DRP_2.configure(this);

            this.CLKGEN_DRP_2.build();
            this.default_map.add_reg(this.CLKGEN_DRP_2, 'h12);
            this.CLKGEN_DRP_3 = new("CLKGEN_DRP_3");
            this.CLKGEN_DRP_3.configure(this);

            this.CLKGEN_DRP_3.build();
            this.default_map.add_reg(this.CLKGEN_DRP_3, 'h14);
            this.adc_output_mem = new("adc_output_mem");
            this.adc_output_mem.configure(this);
            this.adc_output_mem.build();
            this.default_map.add_submap(this.adc_output_mem.default_map, 'h10000);
        endfunction : build
    endclass : adc_regs

endpackage: adc_regs_pkg
