
// This file was autogenerated by PeakRDL-uvm
package chip_regs_dv_pkg;
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    
    // mem - adc_regs::ADC_OUTPUT_MEM
    class adc_regs__ADC_OUTPUT_MEM extends uvm_reg_block;
        `uvm_object_utils(adc_regs__ADC_OUTPUT_MEM)
        rand uvm_mem m_mem;
        
        function new(string name = "adc_regs__ADC_OUTPUT_MEM");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 2.0, UVM_NO_ENDIAN);
            this.m_mem = new("m_mem", 16384, 16, "RO");
            this.m_mem.configure(this);
            this.default_map.add_mem(this.m_mem, 0);
        endfunction : build
    endclass : adc_regs__ADC_OUTPUT_MEM

    // reg - adc_regs::active_passive_reg
    class adc_regs__active_passive_reg extends uvm_reg;
        `uvm_object_utils(adc_regs__active_passive_reg)
        rand uvm_reg_field N_ACTIVE_CYCLES;
        rand uvm_reg_field N_PASSIVE_CYCLES;

        function new(string name = "adc_regs__active_passive_reg");
            super.new(name, 16, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.N_ACTIVE_CYCLES = uvm_reg_field::type_id::create("N_ACTIVE_CYCLES");
            this.N_ACTIVE_CYCLES.configure(this, 8, 0, "RW", 0, 'h1, 1, 1, 1);
            this.N_PASSIVE_CYCLES = uvm_reg_field::type_id::create("N_PASSIVE_CYCLES");
            this.N_PASSIVE_CYCLES.configure(this, 8, 8, "RW", 0, 'h0, 1, 1, 1);
        endfunction : build
    endclass : adc_regs__active_passive_reg

    // reg - adc_regs::FFT_CTRL
    class adc_regs__FFT_CTRL extends uvm_reg;
        `uvm_object_utils(adc_regs__FFT_CTRL)
        rand uvm_reg_field OSR_POWER;
        rand uvm_reg_field NFFT_POWER;
        rand uvm_reg_field INCREMENTAL_MODE_EN;
        rand uvm_reg_field NOISE_SHAPING_EN;
        rand uvm_reg_field N_QUANTIZER_BITS;
        rand uvm_reg_field DWA_EN;
        rand uvm_reg_field DELAY_LINE_CTRL;

        function new(string name = "adc_regs__FFT_CTRL");
            super.new(name, 16, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.OSR_POWER = uvm_reg_field::type_id::create("OSR_POWER");
            this.OSR_POWER.configure(this, 3, 0, "RW", 0, 'h0, 1, 1, 0);
            this.NFFT_POWER = uvm_reg_field::type_id::create("NFFT_POWER");
            this.NFFT_POWER.configure(this, 4, 3, "RW", 0, 'h0, 1, 1, 0);
            this.INCREMENTAL_MODE_EN = uvm_reg_field::type_id::create("INCREMENTAL_MODE_EN");
            this.INCREMENTAL_MODE_EN.configure(this, 1, 7, "RW", 0, 'h0, 1, 1, 0);
            this.NOISE_SHAPING_EN = uvm_reg_field::type_id::create("NOISE_SHAPING_EN");
            this.NOISE_SHAPING_EN.configure(this, 1, 8, "RW", 0, 'h0, 1, 1, 0);
            this.N_QUANTIZER_BITS = uvm_reg_field::type_id::create("N_QUANTIZER_BITS");
            this.N_QUANTIZER_BITS.configure(this, 2, 9, "RW", 0, 'h0, 1, 1, 0);
            this.DWA_EN = uvm_reg_field::type_id::create("DWA_EN");
            this.DWA_EN.configure(this, 1, 11, "RW", 0, 'h0, 1, 1, 0);
            this.DELAY_LINE_CTRL = uvm_reg_field::type_id::create("DELAY_LINE_CTRL");
            this.DELAY_LINE_CTRL.configure(this, 4, 12, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : adc_regs__FFT_CTRL

    // reg - adc_regs::ADC_CTRL
    class adc_regs__ADC_CTRL extends uvm_reg;
        `uvm_object_utils(adc_regs__ADC_CTRL)
        rand uvm_reg_field START_CONVERSION;
        rand uvm_reg_field SYNC_RESET_RB;
        rand uvm_reg_field MAIN_STATE_RB;

        function new(string name = "adc_regs__ADC_CTRL");
            super.new(name, 16, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.START_CONVERSION = uvm_reg_field::type_id::create("START_CONVERSION");
            this.START_CONVERSION.configure(this, 1, 0, "RW", 1, 'h0, 1, 0, 0);
            this.SYNC_RESET_RB = uvm_reg_field::type_id::create("SYNC_RESET_RB");
            this.SYNC_RESET_RB.configure(this, 1, 1, "RO", 1, 'h0, 1, 1, 0);
            this.MAIN_STATE_RB = uvm_reg_field::type_id::create("MAIN_STATE_RB");
            this.MAIN_STATE_RB.configure(this, 4, 2, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : adc_regs__ADC_CTRL

    // reg - adc_regs::CONVERSION_FLAGS
    class adc_regs__CONVERSION_FLAGS extends uvm_reg;
        `uvm_object_utils(adc_regs__CONVERSION_FLAGS)
        rand uvm_reg_field N_VALID_SAMPLES;
        rand uvm_reg_field PREVIOUS_CONVERSION_CORRUPTED;

        function new(string name = "adc_regs__CONVERSION_FLAGS");
            super.new(name, 16, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.N_VALID_SAMPLES = uvm_reg_field::type_id::create("N_VALID_SAMPLES");
            this.N_VALID_SAMPLES.configure(this, 15, 0, "RO", 1, 'h0, 1, 1, 0);
            this.PREVIOUS_CONVERSION_CORRUPTED = uvm_reg_field::type_id::create("PREVIOUS_CONVERSION_CORRUPTED");
            this.PREVIOUS_CONVERSION_CORRUPTED.configure(this, 1, 15, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : adc_regs__CONVERSION_FLAGS

    // addrmap - adc_regs
    class adc_regs extends uvm_reg_block;
        `uvm_object_utils(adc_regs)
        rand adc_regs__ADC_OUTPUT_MEM ADC_OUTPUT_MEM;
        rand adc_regs__active_passive_reg SH_CTRL;
        rand adc_regs__active_passive_reg INT1_CTRL;
        rand adc_regs__active_passive_reg INT2_CTRL;
        rand adc_regs__FFT_CTRL FFT_CTRL;
        rand adc_regs__ADC_CTRL ADC_CTRL;
        rand adc_regs__CONVERSION_FLAGS CONVERSION_FLAGS;

        function new(string name = "adc_regs");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 2, UVM_NO_ENDIAN);
            this.ADC_OUTPUT_MEM = adc_regs__ADC_OUTPUT_MEM::type_id::create("ADC_OUTPUT_MEM");
            this.ADC_OUTPUT_MEM.configure(this);
            this.ADC_OUTPUT_MEM.build();
            this.default_map.add_submap(this.ADC_OUTPUT_MEM.default_map, 'h0);
            this.SH_CTRL = adc_regs__active_passive_reg::type_id::create("SH_CTRL");
            this.SH_CTRL.configure(this);

            this.SH_CTRL.build();
            this.default_map.add_reg(this.SH_CTRL, 'h8000);
            this.INT1_CTRL = adc_regs__active_passive_reg::type_id::create("INT1_CTRL");
            this.INT1_CTRL.configure(this);

            this.INT1_CTRL.build();
            this.default_map.add_reg(this.INT1_CTRL, 'h8002);
            this.INT2_CTRL = adc_regs__active_passive_reg::type_id::create("INT2_CTRL");
            this.INT2_CTRL.configure(this);

            this.INT2_CTRL.build();
            this.default_map.add_reg(this.INT2_CTRL, 'h8004);
            this.FFT_CTRL = adc_regs__FFT_CTRL::type_id::create("FFT_CTRL");
            this.FFT_CTRL.configure(this);

            this.FFT_CTRL.build();
            this.default_map.add_reg(this.FFT_CTRL, 'h8006);
            this.ADC_CTRL = adc_regs__ADC_CTRL::type_id::create("ADC_CTRL");
            this.ADC_CTRL.configure(this);

            this.ADC_CTRL.build();
            this.default_map.add_reg(this.ADC_CTRL, 'h8008);
            this.CONVERSION_FLAGS = adc_regs__CONVERSION_FLAGS::type_id::create("CONVERSION_FLAGS");
            this.CONVERSION_FLAGS.configure(this);

            this.CONVERSION_FLAGS.build();
            this.default_map.add_reg(this.CONVERSION_FLAGS, 'h800a);
        endfunction : build
    endclass : adc_regs

    // reg - dac_regs::AC_CONFIG
    class dac_regs__AC_CONFIG extends uvm_reg;
        `uvm_object_utils(dac_regs__AC_CONFIG)
        rand uvm_reg_field frequency;
        rand uvm_reg_field amplitude;

        function new(string name = "dac_regs__AC_CONFIG");
            super.new(name, 16, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.frequency = uvm_reg_field::type_id::create("frequency");
            this.frequency.configure(this, 4, 0, "RW", 0, 'h0, 1, 1, 0);
            this.amplitude = uvm_reg_field::type_id::create("amplitude");
            this.amplitude.configure(this, 4, 4, "RW", 0, 'hf, 1, 1, 0);
        endfunction : build
    endclass : dac_regs__AC_CONFIG

    // reg - dac_regs::ENABLE
    class dac_regs__ENABLE extends uvm_reg;
        `uvm_object_utils(dac_regs__ENABLE)
        rand uvm_reg_field dacp_enable;
        rand uvm_reg_field dacp_mode;
        rand uvm_reg_field dacn_enable;
        rand uvm_reg_field dacn_mode;
        rand uvm_reg_field dsm_enable;

        function new(string name = "dac_regs__ENABLE");
            super.new(name, 16, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.dacp_enable = uvm_reg_field::type_id::create("dacp_enable");
            this.dacp_enable.configure(this, 1, 0, "RW", 0, 'h0, 1, 1, 0);
            this.dacp_mode = uvm_reg_field::type_id::create("dacp_mode");
            this.dacp_mode.configure(this, 1, 1, "RW", 0, 'h0, 1, 1, 0);
            this.dacn_enable = uvm_reg_field::type_id::create("dacn_enable");
            this.dacn_enable.configure(this, 1, 2, "RW", 0, 'h0, 1, 1, 0);
            this.dacn_mode = uvm_reg_field::type_id::create("dacn_mode");
            this.dacn_mode.configure(this, 1, 3, "RW", 0, 'h0, 1, 1, 0);
            this.dsm_enable = uvm_reg_field::type_id::create("dsm_enable");
            this.dsm_enable.configure(this, 1, 4, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : dac_regs__ENABLE

    // reg - dac_regs::dc_value_reg
    class dac_regs__dc_value_reg extends uvm_reg;
        `uvm_object_utils(dac_regs__dc_value_reg)
        rand uvm_reg_field dc_value;

        function new(string name = "dac_regs__dc_value_reg");
            super.new(name, 16, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.dc_value = uvm_reg_field::type_id::create("dc_value");
            this.dc_value.configure(this, 8, 0, "RW", 0, 'h0, 1, 1, 1);
        endfunction : build
    endclass : dac_regs__dc_value_reg

    // reg - dac_regs::CLK_DIV
    class dac_regs__CLK_DIV extends uvm_reg;
        `uvm_object_utils(dac_regs__CLK_DIV)
        rand uvm_reg_field clk_div_value;

        function new(string name = "dac_regs__CLK_DIV");
            super.new(name, 16, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.clk_div_value = uvm_reg_field::type_id::create("clk_div_value");
            this.clk_div_value.configure(this, 8, 0, "RW", 0, 'h0, 1, 1, 1);
        endfunction : build
    endclass : dac_regs__CLK_DIV

    // reg - dac_regs::STATUS
    class dac_regs__STATUS extends uvm_reg;
        `uvm_object_utils(dac_regs__STATUS)
        rand uvm_reg_field dacp_power;
        rand uvm_reg_field dacn_power;
        rand uvm_reg_field dsm_locked;

        function new(string name = "dac_regs__STATUS");
            super.new(name, 16, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.dacp_power = uvm_reg_field::type_id::create("dacp_power");
            this.dacp_power.configure(this, 2, 0, "RW", 0, 'h0, 1, 1, 0);
            this.dacn_power = uvm_reg_field::type_id::create("dacn_power");
            this.dacn_power.configure(this, 2, 2, "RW", 0, 'h0, 1, 1, 0);
            this.dsm_locked = uvm_reg_field::type_id::create("dsm_locked");
            this.dsm_locked.configure(this, 1, 4, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : dac_regs__STATUS

    // addrmap - dac_regs
    class dac_regs extends uvm_reg_block;
        `uvm_object_utils(dac_regs)
        rand dac_regs__AC_CONFIG AC_CONFIG;
        rand dac_regs__ENABLE ENABLE;
        rand dac_regs__dc_value_reg DACP_DC_VALUE;
        rand dac_regs__dc_value_reg DACN_DC_VALUE;
        rand dac_regs__CLK_DIV CLK_DIV;
        rand dac_regs__STATUS STATUS;

        function new(string name = "dac_regs");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 1, UVM_NO_ENDIAN);
            this.AC_CONFIG = dac_regs__AC_CONFIG::type_id::create("AC_CONFIG");
            this.AC_CONFIG.configure(this);

            this.AC_CONFIG.build();
            this.default_map.add_reg(this.AC_CONFIG, 'h0);
            this.ENABLE = dac_regs__ENABLE::type_id::create("ENABLE");
            this.ENABLE.configure(this);

            this.ENABLE.build();
            this.default_map.add_reg(this.ENABLE, 'h2);
            this.DACP_DC_VALUE = dac_regs__dc_value_reg::type_id::create("DACP_DC_VALUE");
            this.DACP_DC_VALUE.configure(this);

            this.DACP_DC_VALUE.build();
            this.default_map.add_reg(this.DACP_DC_VALUE, 'h4);
            this.DACN_DC_VALUE = dac_regs__dc_value_reg::type_id::create("DACN_DC_VALUE");
            this.DACN_DC_VALUE.configure(this);

            this.DACN_DC_VALUE.build();
            this.default_map.add_reg(this.DACN_DC_VALUE, 'h6);
            this.CLK_DIV = dac_regs__CLK_DIV::type_id::create("CLK_DIV");
            this.CLK_DIV.configure(this);

            this.CLK_DIV.build();
            this.default_map.add_reg(this.CLK_DIV, 'h8);
            this.STATUS = dac_regs__STATUS::type_id::create("STATUS");
            this.STATUS.configure(this);

            this.STATUS.build();
            this.default_map.add_reg(this.STATUS, 'ha);
        endfunction : build
    endclass : dac_regs

    // addrmap - chip_top
    class chip_top extends uvm_reg_block;
        `uvm_object_utils(chip_top)
        rand adc_regs ADC;
        rand dac_regs DAC;

        function new(string name = "chip_top");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 2, UVM_NO_ENDIAN);
            this.ADC = adc_regs::type_id::create("ADC");
            this.ADC.configure(this);
            this.ADC.build();
            this.default_map.add_submap(this.ADC.default_map, 'h0);
            this.DAC = dac_regs::type_id::create("DAC");
            this.DAC.configure(this);
            this.DAC.build();
            this.default_map.add_submap(this.DAC.default_map, 'h80ff);
        endfunction : build
    endclass : chip_top

endpackage: chip_regs_dv_pkg
