// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module dac_regs_mod (
        input wire clk,
        input wire rst,

        axi4lite_intf.slave s_axil,

        input dac_regs_mod_pkg::dac_regs__in_t hwif_in,
        output dac_regs_mod_pkg::dac_regs__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [3:0] cpuif_addr;
    logic [7:0] cpuif_wr_data;
    logic [7:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [7:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    `ifndef SYNTHESIS
        initial begin
            assert_bad_addr_width: assert($bits(s_axil.ARADDR) >= dac_regs_mod_pkg::DAC_REGS_MOD_MIN_ADDR_WIDTH)
                else $error("Interface address width of %0d is too small. Shall be at least %0d bits", $bits(s_axil.ARADDR), dac_regs_mod_pkg::DAC_REGS_MOD_MIN_ADDR_WIDTH);
            assert_bad_data_width: assert($bits(s_axil.WDATA) == dac_regs_mod_pkg::DAC_REGS_MOD_DATA_WIDTH)
                else $error("Interface data width of %0d is incorrect. Shall be %0d bits", $bits(s_axil.WDATA), dac_regs_mod_pkg::DAC_REGS_MOD_DATA_WIDTH);
        end
    `endif

    // Max Outstanding Transactions: 3
    logic [1:0] axil_n_in_flight;
    logic axil_prev_was_rd;
    logic axil_arvalid;
    logic [3:0] axil_araddr;
    logic axil_ar_accept;
    logic axil_awvalid;
    logic [3:0] axil_awaddr;
    logic axil_wvalid;
    logic [7:0] axil_wdata;
    logic [0:0] axil_wstrb;
    logic axil_aw_accept;
    logic axil_resp_acked;

    // Transaction request acceptance
    always_ff @(posedge clk) begin
        if(rst) begin
            axil_prev_was_rd <= '0;
            axil_arvalid <= '0;
            axil_araddr <= '0;
            axil_awvalid <= '0;
            axil_awaddr <= '0;
            axil_wvalid <= '0;
            axil_wdata <= '0;
            axil_wstrb <= '0;
            axil_n_in_flight <= '0;
        end else begin
            // AR* acceptance register
            if(axil_ar_accept) begin
                axil_prev_was_rd <= '1;
                axil_arvalid <= '0;
            end
            if(s_axil.ARVALID && s_axil.ARREADY) begin
                axil_arvalid <= '1;
                axil_araddr <= s_axil.ARADDR;
            end

            // AW* & W* acceptance registers
            if(axil_aw_accept) begin
                axil_prev_was_rd <= '0;
                axil_awvalid <= '0;
                axil_wvalid <= '0;
            end
            if(s_axil.AWVALID && s_axil.AWREADY) begin
                axil_awvalid <= '1;
                axil_awaddr <= s_axil.AWADDR;
            end
            if(s_axil.WVALID && s_axil.WREADY) begin
                axil_wvalid <= '1;
                axil_wdata <= s_axil.WDATA;
                axil_wstrb <= s_axil.WSTRB;
            end

            // Keep track of in-flight transactions
            if((axil_ar_accept || axil_aw_accept) && !axil_resp_acked) begin
                axil_n_in_flight <= axil_n_in_flight + 1'b1;
            end else if(!(axil_ar_accept || axil_aw_accept) && axil_resp_acked) begin
                axil_n_in_flight <= axil_n_in_flight - 1'b1;
            end
        end
    end

    always_comb begin
        s_axil.ARREADY = (!axil_arvalid || axil_ar_accept);
        s_axil.AWREADY = (!axil_awvalid || axil_aw_accept);
        s_axil.WREADY = (!axil_wvalid || axil_aw_accept);
    end

    // Request dispatch
    always_comb begin
        cpuif_wr_data = axil_wdata;
        for(int i=0; i<1; i++) begin
            cpuif_wr_biten[i*8 +: 8] = {8{axil_wstrb[i]}};
        end
        cpuif_req = '0;
        cpuif_req_is_wr = '0;
        cpuif_addr = '0;
        axil_ar_accept = '0;
        axil_aw_accept = '0;

        if(axil_n_in_flight < 2'd3) begin
            // Can safely issue more transactions without overwhelming response buffer
            if(axil_arvalid && !axil_prev_was_rd) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '0;
                cpuif_addr = axil_araddr;
                if(!cpuif_req_stall_rd) axil_ar_accept = '1;
            end else if(axil_awvalid && axil_wvalid) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '1;
                cpuif_addr = axil_awaddr;
                if(!cpuif_req_stall_wr) axil_aw_accept = '1;
            end else if(axil_arvalid) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '0;
                cpuif_addr = axil_araddr;
                if(!cpuif_req_stall_rd) axil_ar_accept = '1;
            end
        end
    end


    // AXI4-Lite Response Logic
    struct {
        logic is_wr;
        logic err;
        logic [7:0] rdata;
    } axil_resp_buffer[4];
    // axil_resp_buffer is intentionally padded to the next power of two despite
    // only requiring 3 entries.
    // This is to avoid quirks in some tools that cannot handle indexing into a non-power-of-2 array.
    // Unused entries are expected to be optimized away


    logic [2:0] axil_resp_wptr;
    logic [2:0] axil_resp_rptr;

    always_ff @(posedge clk) begin
        if(rst) begin
            for(int i=0; i<3; i++) begin
                axil_resp_buffer[i].is_wr <= '0;
                axil_resp_buffer[i].err <= '0;
                axil_resp_buffer[i].rdata <= '0;
            end
            axil_resp_wptr <= '0;
            axil_resp_rptr <= '0;
        end else begin
            // Store responses in buffer until AXI response channel accepts them
            if(cpuif_rd_ack || cpuif_wr_ack) begin
                if(cpuif_rd_ack) begin
                    axil_resp_buffer[axil_resp_wptr[1:0]].is_wr <= '0;
                    axil_resp_buffer[axil_resp_wptr[1:0]].err <= cpuif_rd_err;
                    axil_resp_buffer[axil_resp_wptr[1:0]].rdata <= cpuif_rd_data;

                end else if(cpuif_wr_ack) begin
                    axil_resp_buffer[axil_resp_wptr[1:0]].is_wr <= '1;
                    axil_resp_buffer[axil_resp_wptr[1:0]].err <= cpuif_wr_err;
                end
                if(axil_resp_wptr[1:0] == 2) begin
                    axil_resp_wptr[1:0] <= '0;
                    axil_resp_wptr[2] <= ~axil_resp_wptr[2];
                end else begin
                    axil_resp_wptr[1:0] <= axil_resp_wptr[1:0] + 1'b1;
                end
            end

            // Advance read pointer when acknowledged
            if(axil_resp_acked) begin
                if(axil_resp_rptr[1:0] == 2) begin
                    axil_resp_rptr[1:0] <= '0;
                    axil_resp_rptr[2] <= ~axil_resp_rptr[2];
                end else begin
                    axil_resp_rptr[1:0] <= axil_resp_rptr[1:0] + 1'b1;
                end
            end
        end
    end

    always_comb begin
        axil_resp_acked = '0;
        s_axil.BVALID = '0;
        s_axil.RVALID = '0;
        if(axil_resp_rptr != axil_resp_wptr) begin
            if(axil_resp_buffer[axil_resp_rptr[1:0]].is_wr) begin
                s_axil.BVALID = '1;
                if(s_axil.BREADY) axil_resp_acked = '1;
            end else begin
                s_axil.RVALID = '1;
                if(s_axil.RREADY) axil_resp_acked = '1;
            end
        end

        s_axil.RDATA = axil_resp_buffer[axil_resp_rptr[1:0]].rdata;
        if(axil_resp_buffer[axil_resp_rptr[1:0]].err) begin
            s_axil.BRESP = 2'b10;
            s_axil.RRESP = 2'b10;
        end else begin
            s_axil.BRESP = 2'b00;
            s_axil.RRESP = 2'b00;
        end
    end

    logic cpuif_req_masked;

    // Read latency > write latency. May need to delay next write that follows a read
    logic [0:0] cpuif_req_stall_sr;
    always_ff @(posedge clk) begin
        if(rst) begin
            cpuif_req_stall_sr <= '0;
        end else if(cpuif_req && !cpuif_req_is_wr) begin
            cpuif_req_stall_sr <= '1;
        end else begin
            cpuif_req_stall_sr <= (cpuif_req_stall_sr >> 'd1);
        end
    end
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = cpuif_req_stall_sr[0];
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic [1:0] AC_CONFIG;
        logic [1:0] ENABLE;
        logic [1:0] DACP_DC_VALUE;
        logic [1:0] DACN_DC_VALUE;
        logic [1:0] CLK_DIV;
        logic [1:0] STATUS;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [7:0] decoded_wr_data;
    logic [7:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_invalid_rw;
        is_valid_addr = '1; // No error checking on valid address access
        is_invalid_rw = '0;
        decoded_reg_strb.AC_CONFIG[0] = cpuif_req_masked & (cpuif_addr == 4'h0);
        decoded_reg_strb.AC_CONFIG[1] = cpuif_req_masked & (cpuif_addr == 4'h1);
        decoded_reg_strb.ENABLE[0] = cpuif_req_masked & (cpuif_addr == 4'h2);
        decoded_reg_strb.ENABLE[1] = cpuif_req_masked & (cpuif_addr == 4'h3);
        decoded_reg_strb.DACP_DC_VALUE[0] = cpuif_req_masked & (cpuif_addr == 4'h4);
        decoded_reg_strb.DACP_DC_VALUE[1] = cpuif_req_masked & (cpuif_addr == 4'h5);
        decoded_reg_strb.DACN_DC_VALUE[0] = cpuif_req_masked & (cpuif_addr == 4'h6);
        decoded_reg_strb.DACN_DC_VALUE[1] = cpuif_req_masked & (cpuif_addr == 4'h7);
        decoded_reg_strb.CLK_DIV[0] = cpuif_req_masked & (cpuif_addr == 4'h8);
        decoded_reg_strb.CLK_DIV[1] = cpuif_req_masked & (cpuif_addr == 4'h9);
        decoded_reg_strb.STATUS[0] = cpuif_req_masked & (cpuif_addr == 4'ha);
        decoded_reg_strb.STATUS[1] = cpuif_req_masked & (cpuif_addr == 4'hb);
        decoded_err = (~is_valid_addr | is_invalid_rw) & decoded_req;
    end

    // Pass down signals to next stage
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic [3:0] next;
                logic load_next;
            } frequency;
            struct {
                logic [3:0] next;
                logic load_next;
            } amplitude;
        } AC_CONFIG;
        struct {
            struct {
                logic next;
                logic load_next;
            } dacp_enable;
            struct {
                logic next;
                logic load_next;
            } dacp_mode;
            struct {
                logic next;
                logic load_next;
            } dacn_enable;
            struct {
                logic next;
                logic load_next;
            } dacn_mode;
            struct {
                logic next;
                logic load_next;
            } dsm_enable;
        } ENABLE;
        struct {
            struct {
                logic [7:0] next;
                logic load_next;
            } dc_value;
        } DACP_DC_VALUE;
        struct {
            struct {
                logic [7:0] next;
                logic load_next;
            } dc_value;
        } DACN_DC_VALUE;
        struct {
            struct {
                logic [7:0] next;
                logic load_next;
            } clk_div_value;
        } CLK_DIV;
        struct {
            struct {
                logic [1:0] next;
                logic load_next;
            } dacp_power;
            struct {
                logic [1:0] next;
                logic load_next;
            } dacn_power;
        } STATUS;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic [3:0] value;
            } frequency;
            struct {
                logic [3:0] value;
            } amplitude;
        } AC_CONFIG;
        struct {
            struct {
                logic value;
            } dacp_enable;
            struct {
                logic value;
            } dacp_mode;
            struct {
                logic value;
            } dacn_enable;
            struct {
                logic value;
            } dacn_mode;
            struct {
                logic value;
            } dsm_enable;
        } ENABLE;
        struct {
            struct {
                logic [7:0] value;
            } dc_value;
        } DACP_DC_VALUE;
        struct {
            struct {
                logic [7:0] value;
            } dc_value;
        } DACN_DC_VALUE;
        struct {
            struct {
                logic [7:0] value;
            } clk_div_value;
        } CLK_DIV;
        struct {
            struct {
                logic [1:0] value;
            } dacp_power;
            struct {
                logic [1:0] value;
            } dacn_power;
        } STATUS;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: dac_regs.AC_CONFIG.frequency
    always_comb begin
        automatic logic [3:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.AC_CONFIG.frequency.value;
        load_next_c = '0;
        if(decoded_reg_strb.AC_CONFIG[0] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.AC_CONFIG.frequency.value & ~decoded_wr_biten[3:0]) | (decoded_wr_data[3:0] & decoded_wr_biten[3:0]);
            load_next_c = '1;
        end
        field_combo.AC_CONFIG.frequency.next = next_c;
        field_combo.AC_CONFIG.frequency.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.AC_CONFIG.frequency.value <= 4'h0;
        end else begin
            if(field_combo.AC_CONFIG.frequency.load_next) begin
                field_storage.AC_CONFIG.frequency.value <= field_combo.AC_CONFIG.frequency.next;
            end
        end
    end
    assign hwif_out.AC_CONFIG.frequency.value = field_storage.AC_CONFIG.frequency.value;
    // Field: dac_regs.AC_CONFIG.amplitude
    always_comb begin
        automatic logic [3:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.AC_CONFIG.amplitude.value;
        load_next_c = '0;
        if(decoded_reg_strb.AC_CONFIG[0] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.AC_CONFIG.amplitude.value & ~decoded_wr_biten[7:4]) | (decoded_wr_data[7:4] & decoded_wr_biten[7:4]);
            load_next_c = '1;
        end
        field_combo.AC_CONFIG.amplitude.next = next_c;
        field_combo.AC_CONFIG.amplitude.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.AC_CONFIG.amplitude.value <= 4'hf;
        end else begin
            if(field_combo.AC_CONFIG.amplitude.load_next) begin
                field_storage.AC_CONFIG.amplitude.value <= field_combo.AC_CONFIG.amplitude.next;
            end
        end
    end
    assign hwif_out.AC_CONFIG.amplitude.value = field_storage.AC_CONFIG.amplitude.value;
    // Field: dac_regs.ENABLE.dacp_enable
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.ENABLE.dacp_enable.value;
        load_next_c = '0;
        if(decoded_reg_strb.ENABLE[0] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.ENABLE.dacp_enable.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.ENABLE.dacp_enable.next = next_c;
        field_combo.ENABLE.dacp_enable.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.ENABLE.dacp_enable.value <= 1'h0;
        end else begin
            if(field_combo.ENABLE.dacp_enable.load_next) begin
                field_storage.ENABLE.dacp_enable.value <= field_combo.ENABLE.dacp_enable.next;
            end
        end
    end
    assign hwif_out.ENABLE.dacp_enable.value = field_storage.ENABLE.dacp_enable.value;
    // Field: dac_regs.ENABLE.dacp_mode
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.ENABLE.dacp_mode.value;
        load_next_c = '0;
        if(decoded_reg_strb.ENABLE[0] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.ENABLE.dacp_mode.value & ~decoded_wr_biten[1:1]) | (decoded_wr_data[1:1] & decoded_wr_biten[1:1]);
            load_next_c = '1;
        end
        field_combo.ENABLE.dacp_mode.next = next_c;
        field_combo.ENABLE.dacp_mode.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.ENABLE.dacp_mode.value <= 1'h0;
        end else begin
            if(field_combo.ENABLE.dacp_mode.load_next) begin
                field_storage.ENABLE.dacp_mode.value <= field_combo.ENABLE.dacp_mode.next;
            end
        end
    end
    assign hwif_out.ENABLE.dacp_mode.value = field_storage.ENABLE.dacp_mode.value;
    // Field: dac_regs.ENABLE.dacn_enable
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.ENABLE.dacn_enable.value;
        load_next_c = '0;
        if(decoded_reg_strb.ENABLE[0] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.ENABLE.dacn_enable.value & ~decoded_wr_biten[2:2]) | (decoded_wr_data[2:2] & decoded_wr_biten[2:2]);
            load_next_c = '1;
        end
        field_combo.ENABLE.dacn_enable.next = next_c;
        field_combo.ENABLE.dacn_enable.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.ENABLE.dacn_enable.value <= 1'h0;
        end else begin
            if(field_combo.ENABLE.dacn_enable.load_next) begin
                field_storage.ENABLE.dacn_enable.value <= field_combo.ENABLE.dacn_enable.next;
            end
        end
    end
    assign hwif_out.ENABLE.dacn_enable.value = field_storage.ENABLE.dacn_enable.value;
    // Field: dac_regs.ENABLE.dacn_mode
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.ENABLE.dacn_mode.value;
        load_next_c = '0;
        if(decoded_reg_strb.ENABLE[0] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.ENABLE.dacn_mode.value & ~decoded_wr_biten[3:3]) | (decoded_wr_data[3:3] & decoded_wr_biten[3:3]);
            load_next_c = '1;
        end
        field_combo.ENABLE.dacn_mode.next = next_c;
        field_combo.ENABLE.dacn_mode.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.ENABLE.dacn_mode.value <= 1'h0;
        end else begin
            if(field_combo.ENABLE.dacn_mode.load_next) begin
                field_storage.ENABLE.dacn_mode.value <= field_combo.ENABLE.dacn_mode.next;
            end
        end
    end
    assign hwif_out.ENABLE.dacn_mode.value = field_storage.ENABLE.dacn_mode.value;
    // Field: dac_regs.ENABLE.dsm_enable
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.ENABLE.dsm_enable.value;
        load_next_c = '0;
        if(decoded_reg_strb.ENABLE[0] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.ENABLE.dsm_enable.value & ~decoded_wr_biten[4:4]) | (decoded_wr_data[4:4] & decoded_wr_biten[4:4]);
            load_next_c = '1;
        end
        field_combo.ENABLE.dsm_enable.next = next_c;
        field_combo.ENABLE.dsm_enable.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.ENABLE.dsm_enable.value <= 1'h0;
        end else begin
            if(field_combo.ENABLE.dsm_enable.load_next) begin
                field_storage.ENABLE.dsm_enable.value <= field_combo.ENABLE.dsm_enable.next;
            end
        end
    end
    assign hwif_out.ENABLE.dsm_enable.value = field_storage.ENABLE.dsm_enable.value;
    // Field: dac_regs.DACP_DC_VALUE.dc_value
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.DACP_DC_VALUE.dc_value.value;
        load_next_c = '0;
        if(decoded_reg_strb.DACP_DC_VALUE[0] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.DACP_DC_VALUE.dc_value.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end
        field_combo.DACP_DC_VALUE.dc_value.next = next_c;
        field_combo.DACP_DC_VALUE.dc_value.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.DACP_DC_VALUE.dc_value.value <= 8'h0;
        end else begin
            if(field_combo.DACP_DC_VALUE.dc_value.load_next) begin
                field_storage.DACP_DC_VALUE.dc_value.value <= field_combo.DACP_DC_VALUE.dc_value.next;
            end
        end
    end
    assign hwif_out.DACP_DC_VALUE.dc_value.value = field_storage.DACP_DC_VALUE.dc_value.value;
    // Field: dac_regs.DACN_DC_VALUE.dc_value
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.DACN_DC_VALUE.dc_value.value;
        load_next_c = '0;
        if(decoded_reg_strb.DACN_DC_VALUE[0] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.DACN_DC_VALUE.dc_value.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end
        field_combo.DACN_DC_VALUE.dc_value.next = next_c;
        field_combo.DACN_DC_VALUE.dc_value.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.DACN_DC_VALUE.dc_value.value <= 8'h0;
        end else begin
            if(field_combo.DACN_DC_VALUE.dc_value.load_next) begin
                field_storage.DACN_DC_VALUE.dc_value.value <= field_combo.DACN_DC_VALUE.dc_value.next;
            end
        end
    end
    assign hwif_out.DACN_DC_VALUE.dc_value.value = field_storage.DACN_DC_VALUE.dc_value.value;
    // Field: dac_regs.CLK_DIV.clk_div_value
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CLK_DIV.clk_div_value.value;
        load_next_c = '0;
        if(decoded_reg_strb.CLK_DIV[0] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CLK_DIV.clk_div_value.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end
        field_combo.CLK_DIV.clk_div_value.next = next_c;
        field_combo.CLK_DIV.clk_div_value.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.CLK_DIV.clk_div_value.value <= 8'h0;
        end else begin
            if(field_combo.CLK_DIV.clk_div_value.load_next) begin
                field_storage.CLK_DIV.clk_div_value.value <= field_combo.CLK_DIV.clk_div_value.next;
            end
        end
    end
    assign hwif_out.CLK_DIV.clk_div_value.value = field_storage.CLK_DIV.clk_div_value.value;
    // Field: dac_regs.STATUS.dacp_power
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.STATUS.dacp_power.value;
        load_next_c = '0;
        if(decoded_reg_strb.STATUS[0] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.STATUS.dacp_power.value & ~decoded_wr_biten[1:0]) | (decoded_wr_data[1:0] & decoded_wr_biten[1:0]);
            load_next_c = '1;
        end
        field_combo.STATUS.dacp_power.next = next_c;
        field_combo.STATUS.dacp_power.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.STATUS.dacp_power.value <= 2'h0;
        end else begin
            if(field_combo.STATUS.dacp_power.load_next) begin
                field_storage.STATUS.dacp_power.value <= field_combo.STATUS.dacp_power.next;
            end
        end
    end
    assign hwif_out.STATUS.dacp_power.value = field_storage.STATUS.dacp_power.value;
    // Field: dac_regs.STATUS.dacn_power
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.STATUS.dacn_power.value;
        load_next_c = '0;
        if(decoded_reg_strb.STATUS[0] && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.STATUS.dacn_power.value & ~decoded_wr_biten[3:2]) | (decoded_wr_data[3:2] & decoded_wr_biten[3:2]);
            load_next_c = '1;
        end
        field_combo.STATUS.dacn_power.next = next_c;
        field_combo.STATUS.dacn_power.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.STATUS.dacn_power.value <= 2'h0;
        end else begin
            if(field_combo.STATUS.dacn_power.load_next) begin
                field_storage.STATUS.dacn_power.value <= field_combo.STATUS.dacn_power.next;
            end
        end
    end
    assign hwif_out.STATUS.dacn_power.value = field_storage.STATUS.dacn_power.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic readback_err;
    logic readback_done;
    logic [7:0] readback_data;

    // Assign readback values to a flattened array
    logic [7:0] readback_array[6];
    assign readback_array[0][3:0] = (decoded_reg_strb.AC_CONFIG[0] && !decoded_req_is_wr) ? field_storage.AC_CONFIG.frequency.value : '0;
    assign readback_array[0][7:4] = (decoded_reg_strb.AC_CONFIG[0] && !decoded_req_is_wr) ? field_storage.AC_CONFIG.amplitude.value : '0;
    assign readback_array[1][0:0] = (decoded_reg_strb.ENABLE[0] && !decoded_req_is_wr) ? field_storage.ENABLE.dacp_enable.value : '0;
    assign readback_array[1][1:1] = (decoded_reg_strb.ENABLE[0] && !decoded_req_is_wr) ? field_storage.ENABLE.dacp_mode.value : '0;
    assign readback_array[1][2:2] = (decoded_reg_strb.ENABLE[0] && !decoded_req_is_wr) ? field_storage.ENABLE.dacn_enable.value : '0;
    assign readback_array[1][3:3] = (decoded_reg_strb.ENABLE[0] && !decoded_req_is_wr) ? field_storage.ENABLE.dacn_mode.value : '0;
    assign readback_array[1][4:4] = (decoded_reg_strb.ENABLE[0] && !decoded_req_is_wr) ? field_storage.ENABLE.dsm_enable.value : '0;
    assign readback_array[1][7:5] = '0;
    assign readback_array[2][7:0] = (decoded_reg_strb.DACP_DC_VALUE[0] && !decoded_req_is_wr) ? field_storage.DACP_DC_VALUE.dc_value.value : '0;
    assign readback_array[3][7:0] = (decoded_reg_strb.DACN_DC_VALUE[0] && !decoded_req_is_wr) ? field_storage.DACN_DC_VALUE.dc_value.value : '0;
    assign readback_array[4][7:0] = (decoded_reg_strb.CLK_DIV[0] && !decoded_req_is_wr) ? field_storage.CLK_DIV.clk_div_value.value : '0;
    assign readback_array[5][1:0] = (decoded_reg_strb.STATUS[0] && !decoded_req_is_wr) ? field_storage.STATUS.dacp_power.value : '0;
    assign readback_array[5][3:2] = (decoded_reg_strb.STATUS[0] && !decoded_req_is_wr) ? field_storage.STATUS.dacn_power.value : '0;
    assign readback_array[5][4:4] = (decoded_reg_strb.STATUS[0] && !decoded_req_is_wr) ? hwif_in.STATUS.dsm_locked.next : '0;
    assign readback_array[5][7:5] = '0;

    // Reduce the array
    always_comb begin
        automatic logic [7:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
        readback_data_var = '0;
        for(int i=0; i<6; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    always_ff @(posedge clk) begin
        if(rst) begin
            cpuif_rd_ack <= '0;
            cpuif_rd_data <= '0;
            cpuif_rd_err <= '0;
        end else begin
            cpuif_rd_ack <= readback_done;
            cpuif_rd_data <= readback_data;
            cpuif_rd_err <= readback_err;
        end
    end

endmodule
