// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package dac_regs_mod_pkg;

    localparam DAC_REGS_MOD_DATA_WIDTH = 8;
    localparam DAC_REGS_MOD_MIN_ADDR_WIDTH = 4;
    localparam DAC_REGS_MOD_SIZE = 'hc;

    typedef struct {
        logic next;
    } dac_regs__STATUS__dsm_locked__in_t;

    typedef struct {
        dac_regs__STATUS__dsm_locked__in_t dsm_locked;
    } dac_regs__STATUS__in_t;

    typedef struct {
        dac_regs__STATUS__in_t STATUS;
    } dac_regs__in_t;

    typedef struct {
        logic [3:0] value;
    } dac_regs__AC_CONFIG__frequency__out_t;

    typedef struct {
        logic [3:0] value;
    } dac_regs__AC_CONFIG__amplitude__out_t;

    typedef struct {
        dac_regs__AC_CONFIG__frequency__out_t frequency;
        dac_regs__AC_CONFIG__amplitude__out_t amplitude;
    } dac_regs__AC_CONFIG__out_t;

    typedef struct {
        logic value;
    } dac_regs__ENABLE__dacp_enable__out_t;

    typedef struct {
        logic value;
    } dac_regs__ENABLE__dacp_mode__out_t;

    typedef struct {
        logic value;
    } dac_regs__ENABLE__dacn_enable__out_t;

    typedef struct {
        logic value;
    } dac_regs__ENABLE__dacn_mode__out_t;

    typedef struct {
        logic value;
    } dac_regs__ENABLE__dsm_enable__out_t;

    typedef struct {
        dac_regs__ENABLE__dacp_enable__out_t dacp_enable;
        dac_regs__ENABLE__dacp_mode__out_t dacp_mode;
        dac_regs__ENABLE__dacn_enable__out_t dacn_enable;
        dac_regs__ENABLE__dacn_mode__out_t dacn_mode;
        dac_regs__ENABLE__dsm_enable__out_t dsm_enable;
    } dac_regs__ENABLE__out_t;

    typedef struct {
        logic [7:0] value;
    } dac_regs__dc_value_reg__dc_value__out_t;

    typedef struct {
        dac_regs__dc_value_reg__dc_value__out_t dc_value;
    } dac_regs__dc_value_reg__out_t;

    typedef struct {
        logic [7:0] value;
    } dac_regs__CLK_DIV__clk_div_value__out_t;

    typedef struct {
        dac_regs__CLK_DIV__clk_div_value__out_t clk_div_value;
    } dac_regs__CLK_DIV__out_t;

    typedef struct {
        logic [1:0] value;
    } dac_regs__STATUS__dacp_power__out_t;

    typedef struct {
        logic [1:0] value;
    } dac_regs__STATUS__dacn_power__out_t;

    typedef struct {
        dac_regs__STATUS__dacp_power__out_t dacp_power;
        dac_regs__STATUS__dacn_power__out_t dacn_power;
    } dac_regs__STATUS__out_t;

    typedef struct {
        dac_regs__AC_CONFIG__out_t AC_CONFIG;
        dac_regs__ENABLE__out_t ENABLE;
        dac_regs__dc_value_reg__out_t DACP_DC_VALUE;
        dac_regs__dc_value_reg__out_t DACN_DC_VALUE;
        dac_regs__CLK_DIV__out_t CLK_DIV;
        dac_regs__STATUS__out_t STATUS;
    } dac_regs__out_t;

    typedef enum logic {
        dac_regs__frequency_mode_e__DC = 'h0,
        dac_regs__frequency_mode_e__AC = 'h1
    } dac_regs__frequency_mode_e_e;
endpackage
